/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
import java.awt.BorderLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Calendar;

public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrin = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        BotonUsuario = new javax.swing.JButton();
        BotonCalendario = new javax.swing.JButton();
        BotonNotas = new javax.swing.JButton();
        BotonTareas = new javax.swing.JButton();
        BotonIniciarS = new javax.swing.JButton();
        BotonAsignaturas = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrin.setBackground(new java.awt.Color(255, 255, 255));

        PanelMenu.setBackground(new java.awt.Color(102, 102, 255));
        PanelMenu.setPreferredSize(new java.awt.Dimension(200, 675));

        BotonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva1.png"))); // NOI18N
        BotonUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 240)));
        BotonUsuario.setPreferredSize(new java.awt.Dimension(200, 60));
        BotonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUsuarioActionPerformed(evt);
            }
        });

        BotonCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva2.png"))); // NOI18N
        BotonCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 240)));
        BotonCalendario.setPreferredSize(new java.awt.Dimension(200, 60));
        BotonCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalendarioActionPerformed(evt);
            }
        });

        BotonNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImagenNotas.png"))); // NOI18N
        BotonNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 240)));
        BotonNotas.setPreferredSize(new java.awt.Dimension(200, 60));
        BotonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNotasActionPerformed(evt);
            }
        });

        BotonTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImagenTareas.png"))); // NOI18N
        BotonTareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 240)));
        BotonTareas.setPreferredSize(new java.awt.Dimension(200, 60));
        BotonTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTareasActionPerformed(evt);
            }
        });

        BotonIniciarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImagenIniciarS.png"))); // NOI18N
        BotonIniciarS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 240)));
        BotonIniciarS.setPreferredSize(new java.awt.Dimension(200, 60));
        BotonIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarSActionPerformed(evt);
            }
        });

        BotonAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImagenAsignaturas.png"))); // NOI18N
        BotonAsignaturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 240)));
        BotonAsignaturas.setPreferredSize(new java.awt.Dimension(200, 60));
        BotonAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAsignaturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonNotas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonIniciarS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(BotonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(BotonIniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(1000, 675));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrinLayout = new javax.swing.GroupLayout(PanelPrin);
        PanelPrin.setLayout(PanelPrinLayout);
        PanelPrinLayout.setHorizontalGroup(
            PanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrinLayout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrinLayout.setVerticalGroup(
            PanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrinLayout.createSequentialGroup()
                .addGroup(PanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalendarioActionPerformed
        PanelCalendario p2 = new PanelCalendario();
        p2.setSize(1000,675);
        p2.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p2,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();    }//GEN-LAST:event_BotonCalendarioActionPerformed

    private void BotonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUsuarioActionPerformed
        PanelUsuario p4 = new PanelUsuario();
        p4.setSize(1000,675);
        p4.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p4,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();    }//GEN-LAST:event_BotonUsuarioActionPerformed

    private void BotonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNotasActionPerformed
        PanelNotas p3 = new PanelNotas();
        p3.setSize(1000,675);
        p3.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p3,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonNotasActionPerformed

    
    
    private void BotonTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTareasActionPerformed
        PanelTarea p1 = new PanelTarea();
        p1.setSize(1000,675);
        p1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonTareasActionPerformed

    private void BotonIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIniciarSActionPerformed

    private void BotonAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAsignaturasActionPerformed
        PanelAsignaturas p6 = new PanelAsignaturas();
        p6.setSize(1000,675);
        p6.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p6,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();        contenido.repaint();        contenido.repaint();        contenido.repaint();        contenido.repaint();        contenido.repaint();        contenido.repaint();    }//GEN-LAST:event_BotonAsignaturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAsignaturas;
    private javax.swing.JButton BotonCalendario;
    private javax.swing.JButton BotonIniciarS;
    private javax.swing.JButton BotonNotas;
    private javax.swing.JButton BotonTareas;
    private javax.swing.JButton BotonUsuario;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPrin;
    private javax.swing.JPanel contenido;
    // End of variables declaration//GEN-END:variables
}
