/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
import java.awt.*;
public class PanelCalendario extends javax.swing.JPanel {
 
    /**
     * Creates new form Panel1
     */
    public PanelCalendario() {
        initComponents();
                configurarTabla();
    }

    
    private void configurarTabla() {
        calendarioMes.setFont(new Font("SansSerif", Font.PLAIN, 14)); // Fuente Serif, tamaño 14, estilo normal
        calendarioMes.setRowHeight(0, 20); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(1, 60); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(2, 20); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(3, 60); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(4, 20); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(5, 60); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(6, 20); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(7, 60); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(8, 20); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(9, 60); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(10, 20); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setRowHeight(11, 60); // Establece la altura de la primera fila a 40 píxeles
        calendarioMes.setValueAt(1, 0, 0); // Fila 0, Columna 0
        calendarioMes.setValueAt(2, 0, 1); // Fila 0, Columna 0
        calendarioMes.setValueAt(3, 0, 2); // Fila 0, Columna 0
        calendarioMes.setValueAt(4, 0, 3); // Fila 0, Columna 0
        calendarioMes.setValueAt(5, 0, 4); // Fila 0, Columna 0
        calendarioMes.setValueAt(6, 0, 5); // Fila 0, Columna 0
        calendarioMes.setValueAt(7, 0, 6); // Fila 0, Columna 0
        calendarioMes.setValueAt(8, 2, 0); // Fila 0, Columna 0
        calendarioMes.setValueAt(9, 2, 1); // Fila 0, Columna 0
        calendarioMes.setValueAt(10, 2, 2); // Fila 0, Columna 0
        calendarioMes.setValueAt(11, 2, 3); // Fila 0, Columna 0
        calendarioMes.setValueAt(12, 2, 4); // Fila 0, Columna 0
        calendarioMes.setValueAt(13, 2, 5); // Fila 0, Columna 0
        calendarioMes.setValueAt(14, 2, 6); // Fila 0, Columna 0
        calendarioMes.setValueAt(15, 4, 0); // Fila 0, Columna 0
        calendarioMes.setValueAt(16, 4, 1); // Fila 0, Columna 0
        calendarioMes.setValueAt(17, 4, 2); // Fila 0, Columna 0
        calendarioMes.setValueAt(18, 4, 3); // Fila 0, Columna 0
        calendarioMes.setValueAt(19, 4, 4); // Fila 0, Columna 0
        calendarioMes.setValueAt(20, 4, 5); // Fila 0, Columna 0
        calendarioMes.setValueAt(21, 4, 6); // Fila 0, Columna 0
        calendarioMes.setValueAt(22, 6, 0); // Fila 0, Columna 0
        calendarioMes.setValueAt(23, 6, 1); // Fila 0, Columna 0
        calendarioMes.setValueAt(24, 6, 2); // Fila 0, Columna 0
        calendarioMes.setValueAt(25, 6, 3); // Fila 0, Columna 0
        calendarioMes.setValueAt(26, 6, 4); // Fila 0, Columna 0
        calendarioMes.setValueAt(27, 6, 5); // Fila 0, Columna 0
        calendarioMes.setValueAt(28, 6, 6); // Fila 0, Columna 0
        calendarioMes.setValueAt(29, 8, 0); // Fila 0, Columna 0
        calendarioMes.setValueAt(30, 8, 1); // Fila 0, Columna 0




    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        calendarioMes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1000, 675));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 675));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(978, 1000));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 50)); // NOI18N
        jLabel1.setText("CALENDARIO");
        jLabel1.setPreferredSize(new java.awt.Dimension(52, 16));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(910, 510));

        calendarioMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"
            }
        ));
        calendarioMes.setPreferredSize(new java.awt.Dimension(910, 480));
        calendarioMes.setRowHeight(60);
        jScrollPane2.setViewportView(calendarioMes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable calendarioMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
