
//import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;

public class PanelNotas extends javax.swing.JPanel {

 
    private SinglyLinkedList<nota> colaDeNotas;
    private nota notaPrueba;
    private NotaListOperations colaDeNotasOp;
    
    public PanelNotas() {
        initComponents();
        configurarTablaNotas();
        colaDeNotas = new SinglyLinkedList<>();
        colaDeNotasOp = new NotaListOperations(colaDeNotas);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDeNotas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BotonAgregarNota = new javax.swing.JButton();
        jTextFieldPorcentaje = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        BotonLimpiarTablaNotas = new javax.swing.JButton();
        LabelPromedio = new javax.swing.JLabel();
        LabelNotaAcumulada = new javax.swing.JLabel();
        LabelNotaMinima = new javax.swing.JLabel();
        LabelAdvertencia = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 675));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 675));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(978, 1000));

        tablaDeNotas.setBackground(new java.awt.Color(249, 250, 250));
        tablaDeNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "%", "Nombre", "Nota"
            }
        ));
        tablaDeNotas.setGridColor(new java.awt.Color(204, 204, 204));
        tablaDeNotas.setRowHeight(25);
        tablaDeNotas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tablaDeNotas);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 50)); // NOI18N
        jLabel2.setText("NOTAS");
        jLabel2.setPreferredSize(new java.awt.Dimension(52, 16));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel3.setText("Selecciona la asignatura:");
        jLabel3.setPreferredSize(new java.awt.Dimension(52, 16));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignatura 1", "Asignatura 2", "Asignatura 3" }));

        BotonAgregarNota.setText("Agregar");
        BotonAgregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNotaActionPerformed(evt);
            }
        });

        jTextFieldPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPorcentajeActionPerformed(evt);
            }
        });

        BotonLimpiarTablaNotas.setText("Limpiar");
        BotonLimpiarTablaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarTablaNotasActionPerformed(evt);
            }
        });

        LabelPromedio.setBackground(new java.awt.Color(102, 102, 102));
        LabelPromedio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LabelPromedio.setForeground(new java.awt.Color(51, 51, 51));

        LabelNotaAcumulada.setBackground(new java.awt.Color(102, 102, 102));
        LabelNotaAcumulada.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LabelNotaAcumulada.setForeground(new java.awt.Color(51, 51, 51));

        LabelNotaMinima.setBackground(new java.awt.Color(102, 102, 102));
        LabelNotaMinima.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LabelNotaMinima.setForeground(new java.awt.Color(51, 51, 51));

        LabelAdvertencia.setBackground(new java.awt.Color(204, 204, 204));
        LabelAdvertencia.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LabelAdvertencia.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LabelNotaAcumulada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelNotaMinima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(BotonAgregarNota)
                                .addGap(18, 18, 18)
                                .addComponent(BotonLimpiarTablaNotas))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonAgregarNota)
                        .addComponent(BotonLimpiarTablaNotas))
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNotaAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNotaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void configurarTablaNotas() {
        // Crear y establecer el modelo de la tabla
        NonEditableTableModel modeloTabla = new NonEditableTableModel(
            new Object[] {"%", "Nombre", "Nota"}, // Nombres de las columnas
            0 // Número inicial de filas
        );
        tablaDeNotas.setModel(modeloTabla);

        // Configurar las características visuales de la tabla
        tablaDeNotas.setFont(new Font("SansSerif", Font.PLAIN, 14)); // Fuente Serif, tamaño 14, estilo normal

        // Establecer el ancho de las columnas
        TableColumn columnaPorcentaje = tablaDeNotas.getColumnModel().getColumn(0);
        columnaPorcentaje.setPreferredWidth(50);

        TableColumn columnaNombre = tablaDeNotas.getColumnModel().getColumn(1);
        columnaNombre.setPreferredWidth(400);

        TableColumn columnaValor = tablaDeNotas.getColumnModel().getColumn(2);
        columnaValor.setPreferredWidth(50);
    }


    
    private void BotonAgregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNotaActionPerformed
        NonEditableTableModel modeloTabla = (NonEditableTableModel)tablaDeNotas.getModel();
        String nombre = jTextFieldNombre.getText();
        String valor = jTextFieldValor.getText();
        String porcentaje = jTextFieldPorcentaje.getText();

        while (!nombre.equals("")){
            
            notaPrueba = new nota(Double.parseDouble(valor), nombre, Double.parseDouble(porcentaje));
            colaDeNotas.pushBack(notaPrueba);

            SinglyLinkedList.Node<nota> current = colaDeNotas.topFrontNode();

                modeloTabla.setRowCount(0);

             while (current != null) {
                modeloTabla.addRow(current.key.toArray());
                current = current.next;
            }
            jTextFieldNombre.setText("");
            nombre = "";
        }
        LabelPromedio.setText("Promedio: " + colaDeNotasOp.promedio());
        LabelNotaAcumulada.setText("Nota Acumulada: " + colaDeNotasOp.notaAcumulada());
        LabelNotaMinima.setText("Nota mínima (en el " + colaDeNotasOp.notaMinima()[1] + 
                "% restante) para pasar la materia: " + colaDeNotasOp.notaMinima()[0]);
        if (colaDeNotasOp.sumaPorcentajes() > 100.5){
            LabelAdvertencia.setText("ADVERTENCIA: La suma de los porcentajes es mayor a 100");
        }
    }//GEN-LAST:event_BotonAgregarNotaActionPerformed

    private void jTextFieldPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPorcentajeActionPerformed

    private void BotonLimpiarTablaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarTablaNotasActionPerformed
        colaDeNotas.clear();
        NonEditableTableModel modeloTabla = (NonEditableTableModel)tablaDeNotas.getModel();
        modeloTabla.setRowCount(0);
        jTextFieldNombre.setText("");
        jTextFieldValor.setText("");
        jTextFieldPorcentaje.setText("");
        LabelPromedio.setText("");
        LabelNotaAcumulada.setText("");
        LabelNotaMinima.setText("");
        LabelAdvertencia.setText("");

    }//GEN-LAST:event_BotonLimpiarTablaNotasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarNota;
    private javax.swing.JButton BotonLimpiarTablaNotas;
    private javax.swing.JLabel LabelAdvertencia;
    private javax.swing.JLabel LabelNotaAcumulada;
    private javax.swing.JLabel LabelNotaMinima;
    private javax.swing.JLabel LabelPromedio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPorcentaje;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTable tablaDeNotas;
    // End of variables declaration//GEN-END:variables
}

class NonEditableTableModel extends DefaultTableModel {
    public NonEditableTableModel(Object[] columnNames, int rowCount) {
        super(columnNames, rowCount);
    }

    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // Las celdas no son editables
    }
    
}
